Repository NLL-MoneyWise/MoneyWise, pull requests merged in 2025-03, with the labels that each got.

#44 feat: cloud front를 활용하여 영수증 이미지들의 url을 모두 반환하는 기능 추가
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/backend/backend/BackendApplication.java
  backend/src/main/java/backend/backend/controller/ReceiptController.java
  backend/src/main/java/backend/backend/controller/UploadController.java
  backend/src/main/java/backend/backend/domain/Receipt.java
  backend/src/main/java/backend/backend/dto/receipt/model/ReceiptUrlInfo.java
  backend/src/main/java/backend/backend/dto/receipt/response/GetAllReceiptPresignedUrlResponse.java
  backend/src/main/java/backend/backend/repository/ReceiptRepository.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/main/java/backend/backend/service/S3Service.java
  backend/src/main/resources/application.properties
  backend/src/test/java/backend/backend/controller/ReceiptControllerTest.java
  backend/src/test/java/backend/backend/service/S3ServiceIntegrationTest.java
  backend/src/test/resources/application.properties
Labels: ✨feature, 백엔드

#46 렌딩 페이지 개발
  frontend/package-lock.json
  frontend/package.json
  frontend/public/device.svg
  frontend/src/app/(common)/(auth)/join/page.tsx
  frontend/src/app/(common)/(auth)/layout.tsx
  frontend/src/app/(common)/(auth)/login/page.tsx
  frontend/src/app/(common)/layout.tsx
  frontend/src/app/common/components/ArrowIcon/ArrowIcon.tsx
  frontend/src/app/common/components/Articles/InstructionArticle/InstructionArticle.tsx
  frontend/src/app/common/components/Articles/IntroduceArticle/IntroduceArticle.tsx
  frontend/src/app/common/components/Button/Button.tsx
  frontend/src/app/common/components/DeviceImg/DeviceImg.stories.tsx
  frontend/src/app/common/components/DeviceImg/DeviceImg.tsx
  frontend/src/app/common/components/Header/Header.stories.tsx
  frontend/src/app/common/components/Header/Header.tsx
  frontend/src/app/common/components/Logo/Logo.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/middleware.ts
  frontend/tailwind.config.ts
Labels: 🎨design, ✨feature, 프론트엔드

#48 Feature/facade
  backend/src/main/java/backend/backend/controller/FacadeController.java
  backend/src/main/java/backend/backend/controller/ReceiptController.java
  backend/src/main/java/backend/backend/dto/consumption/model/ConsumptionItem.java
  backend/src/main/java/backend/backend/dto/consumption/request/ConsumptionsSaveRequest.java
  backend/src/main/java/backend/backend/dto/facade/request/FacadeConsumptionsAnalyzeRequest.java
  backend/src/main/java/backend/backend/dto/facade/request/FacadeReceiptProcessRequest.java
  backend/src/main/java/backend/backend/dto/facade/response/FacadeConsumptionsAnalyzeResponse.java
  backend/src/main/java/backend/backend/dto/facade/response/FacadeReceiptProcessResponse.java
  backend/src/main/java/backend/backend/dto/receipt/model/ReceiptItem.java
  backend/src/main/java/backend/backend/dto/receipt/response/ReceiptAnalyzeResponse.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryImpl.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/FacadeService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/main/java/backend/backend/service/S3Service.java
  backend/src/test/java/backend/backend/controller/ConsumptionControllerTest.java
  backend/src/test/java/backend/backend/controller/FacadeControllerTest.java
  backend/src/test/java/backend/backend/controller/ReceiptControllerTest.java
  backend/src/test/java/backend/backend/service/ConsumptionServiceTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
Labels: ✨feature, 백엔드

#49 feat: 카카오 로그인 및 회원가입 기능 구현
  backend/src/main/java/backend/backend/component/AuthServiceFactory.java
  backend/src/main/java/backend/backend/controller/AuthController.java
  backend/src/main/java/backend/backend/domain/User.java
  backend/src/main/java/backend/backend/dto/auth/request/BaseLoginRequest.java
  backend/src/main/java/backend/backend/dto/auth/request/BaseSignupRequest.java
  backend/src/main/java/backend/backend/dto/auth/request/KakaoLoginRequest.java
  backend/src/main/java/backend/backend/dto/auth/request/KakaoSignupRequest.java
  backend/src/main/java/backend/backend/dto/auth/request/LocalLoginRequest.java
  backend/src/main/java/backend/backend/dto/auth/request/LocalSignupRequest.java
  backend/src/main/java/backend/backend/dto/auth/response/KakaoLoginResponse.java
  backend/src/main/java/backend/backend/dto/auth/response/KakaoSignupResponse.java
  backend/src/main/java/backend/backend/dto/auth/response/KakaoTokenApiResponse.java
  backend/src/main/java/backend/backend/dto/auth/response/KakaoUserInfoApiResponse.java
  backend/src/main/java/backend/backend/dto/facade/response/FacadeConsumptionsAnalyzeResponse.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryImpl.java
  backend/src/main/java/backend/backend/repository/UserRepository.java
  backend/src/main/java/backend/backend/service/AuthService.java
  backend/src/main/java/backend/backend/service/KakaoAuthService.java
  backend/src/main/java/backend/backend/service/LocalAuthService.java
  backend/src/main/java/backend/backend/service/S3Service.java
  backend/src/main/resources/application.properties
  backend/src/test/java/backend/backend/controller/AuthControllerTest.java
  backend/src/test/java/backend/backend/service/AuthServiceTest.java
Labels: ✨feature, 백엔드

#50 캘린더 페이지 개발
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(common)/(auth)/layout.tsx
  frontend/src/app/(common)/(auth)/login/page.tsx
  frontend/src/app/(common)/layout.tsx
  frontend/src/app/(diary)/calendar/page.tsx
  frontend/src/app/(diary)/layout.tsx
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/components/SignUpForm/SignUpForm.tsx
  frontend/src/app/common/components/Articles/IntroduceArticle/IntroduceArticle.tsx
  frontend/src/app/common/components/Button/Button.tsx
  frontend/src/app/common/components/FloatingButton/FloatingButton.stories.tsx
  frontend/src/app/common/components/FloatingButton/FloatingButton.tsx
  frontend/src/app/common/components/Header/Header.tsx
  frontend/src/app/common/components/Input/InputField.tsx
  frontend/src/app/common/components/Logo/Logo.tsx
  frontend/src/app/common/components/TopBar/TopBar.tsx
  frontend/src/app/diary/components/Calendar/Calendar.stories.tsx
  frontend/src/app/diary/components/Calendar/Calendar.tsx
  frontend/src/app/diary/components/Calendar/calendar.css
  frontend/src/app/page.tsx
Labels: ✨feature

#51 업로드 페이지 개발
  frontend/src/app/(upload)/layout.tsx
  frontend/src/app/(upload)/upload/page.tsx
  frontend/src/app/common/components/FileUpload/UploadButton.tsx
  frontend/src/app/common/components/FloatingButton/FloatingButton.tsx
Labels: ✨feature

#54 Enhancement/receipt analyze consumption save flow
  backend/src/main/java/backend/backend/controller/FacadeController.java
  backend/src/main/java/backend/backend/controller/ReceiptController.java
  backend/src/main/java/backend/backend/domain/Consumption.java
  backend/src/main/java/backend/backend/domain/Receipt.java
  backend/src/main/java/backend/backend/dto/consumption/model/ConsumptionItem.java
  backend/src/main/java/backend/backend/dto/consumption/request/ConsumptionsSaveRequest.java
  backend/src/main/java/backend/backend/dto/receipt/model/ReceiptItem.java
  backend/src/main/java/backend/backend/dto/receipt/response/ReceiptAnalyzeResponse.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/test/java/backend/backend/service/ConsumptionServiceTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
Labels: ♻️ refactor, 백엔드

#57 업로드 페이지 개발
  frontend/src/app/(upload)/layout.tsx
  frontend/src/app/(upload)/upload/page.tsx
  frontend/src/app/common/components/Button/Button.tsx
  frontend/src/app/common/components/Modal/Modal.tsx
  frontend/src/app/upload/components/PreviewImg/PreviewImg.tsx
  frontend/tailwind.config.ts
Labels: 🎨design, ✨feature

#59 [Eenhancement] 소비 저장 기능 개선
  backend/src/main/java/backend/backend/controller/FacadeController.java
  backend/src/main/java/backend/backend/controller/MemoController.java
  backend/src/main/java/backend/backend/domain/Memo.java
  backend/src/main/java/backend/backend/domain/memo/Memo.java
  backend/src/main/java/backend/backend/domain/memo/primaryKey/MemoId.java
  backend/src/main/java/backend/backend/dto/memo/model/MemoDTO.java
  backend/src/main/java/backend/backend/dto/memo/request/CreateMemoRequest.java
  backend/src/main/java/backend/backend/dto/memo/request/UpdateMemoRequest.java
  backend/src/main/java/backend/backend/dto/memo/response/CreateMemoResponse.java
  backend/src/main/java/backend/backend/dto/memo/response/GetAllMemosResponse.java
  backend/src/main/java/backend/backend/exception/BaseException.java
  backend/src/main/java/backend/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/backend/repository/MemoRepository.java
  backend/src/main/java/backend/backend/security/config/SecurityConfig.java
  backend/src/main/java/backend/backend/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/MemoService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/test/java/backend/backend/controller/MemoControllerTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
Labels: ♻️ refactor, 백엔드
