Repository NLL-MoneyWise/MoneyWise, pull requests merged in 2025-05, with the labels that each got.

#65 메모 api 연동
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(diary)/calendar/page.tsx
  frontend/src/app/QueryProvider.tsx
  frontend/src/app/api/auth/check/route.ts
  frontend/src/app/auth/api/action.ts
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/respository.ts
  frontend/src/app/common/components/Input/InputField.tsx
  frontend/src/app/common/components/Modal/Modal.tsx
  frontend/src/app/common/hooks/useModal.tsx
  frontend/src/app/common/util/api.ts
  frontend/src/app/common/util/errorHandler.ts
  frontend/src/app/diary/components/Calendar/Calendar.stories.tsx
  frontend/src/app/diary/components/Calendar/Calendar.tsx
  frontend/src/app/diary/components/CalendarButton/CalendarButton.stories.tsx
  frontend/src/app/diary/components/CalendarButton/CalendarButton.tsx
  frontend/src/app/diary/components/DatePicker/DatePicker.css
  frontend/src/app/diary/components/DatePicker/DatePicker.stories.tsx
  frontend/src/app/diary/components/DatePicker/DatePicker.tsx
  frontend/src/app/diary/components/EventForm/EventForm.stories.tsx
  frontend/src/app/diary/components/EventForm/EventForm.tsx
  frontend/src/app/diary/hooks/useDiary.ts
  frontend/src/app/diary/repository.ts
  frontend/src/app/diary/types/request/index.ts
  frontend/src/app/diary/types/request/request-memo.ts
  frontend/src/app/diary/types/response/index.ts
  frontend/src/app/diary/types/response/reponse-memo.ts
  frontend/src/app/diary/util/formatDate.ts
  frontend/src/middleware.ts
Labels: ✨feature, 프론트엔드

#71 업로드 api 연동
  frontend/src/app/(upload)/upload/page.tsx
  frontend/src/app/QueryProvider.tsx
  frontend/src/app/common/components/FloatingButton/FloatingButton.tsx
  frontend/src/app/common/components/Header/Header.tsx
  frontend/src/app/common/util/api.ts
  frontend/src/app/diary/components/Calendar/Calendar.tsx
  frontend/src/app/page.tsx
  frontend/src/app/upload/hooks/useUpload.tsx
  frontend/src/app/upload/respository.ts
  frontend/src/app/upload/types/reponse/reponse-upload.ts
  frontend/src/app/upload/types/request/index.ts
  frontend/src/app/upload/types/request/request-recipt.ts
Labels: ✨feature, 프론트엔드

#74 [Feature] 회원 탈퇴 기능 추
  backend/src/main/java/backend/backend/BackendApplication.java
  backend/src/main/java/backend/backend/controller/AuthController.java
  backend/src/main/java/backend/backend/controller/ConsumptionController.java
  backend/src/main/java/backend/backend/controller/MemoController.java
  backend/src/main/java/backend/backend/controller/ReceiptController.java
  backend/src/main/java/backend/backend/dto/auth/response/DeleteUserResponse.java
  backend/src/main/java/backend/backend/security/config/SecurityConfig.java
  backend/src/main/java/backend/backend/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/backend/backend/security/jwt/JwtUtils.java
  backend/src/main/java/backend/backend/service/AuthService.java
  backend/src/main/java/backend/backend/service/UserService.java
Labels: ✨feature, 백엔드

#73 chore : 소비 분석 api 연동
  frontend/src/app/common/util/api.ts
Labels: ✏️chore, 🎨design, ✨feature, 프론트엔드

#76 [Feature] 소득액 및 고정 지출액 변경 기능 추가
  backend/src/main/java/backend/backend/controller/AuthController.java
  backend/src/main/java/backend/backend/controller/UserController.java
  backend/src/main/java/backend/backend/domain/User.java
  backend/src/main/java/backend/backend/dto/user/response/UserFixedCostUpdateResponse.java
  backend/src/main/java/backend/backend/dto/user/response/UserIncomeSaveAndUpdateResponse.java
  backend/src/main/java/backend/backend/repository/UserRepository.java
  backend/src/main/java/backend/backend/service/UserService.java
  backend/src/test/java/backend/backend/controller/AuthControllerTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
Labels: ✨feature, 백엔드

#80 [Feature] 소비 내역 변경, 조회, 삭제 기능 추가
  backend/src/main/java/backend/backend/controller/ConsumptionController.java
  backend/src/main/java/backend/backend/domain/Consumption.java
  backend/src/main/java/backend/backend/domain/Receipt.java
  backend/src/main/java/backend/backend/dto/consumption/request/ConsumptionsUpdateRequest.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsDeleteAllResponse.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsDeleteOneResponse.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsFindAllResponse.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsFindOneResponse.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsUpdateResponse.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepository.java
  backend/src/main/java/backend/backend/repository/ReceiptRepository.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
Labels: ✨feature, 백엔드

#82 feat: 기간 내 일별 소비 분석 기능 추가
  backend/nginx/nginx.conf
  backend/src/main/java/backend/backend/controller/AuthController.java
  backend/src/main/java/backend/backend/controller/ConsumptionController.java
  backend/src/main/java/backend/backend/controller/HealthCheckController.java
  backend/src/main/java/backend/backend/dto/consumption/model/ByCategory.java
  backend/src/main/java/backend/backend/dto/consumption/model/DailyFindByCategoryQueryDTO.java
  backend/src/main/java/backend/backend/dto/consumption/model/DailyFindStoreExpenseQueryDTO.java
  backend/src/main/java/backend/backend/dto/consumption/model/DailyFindTopExpenseQueryDTO.java
  backend/src/main/java/backend/backend/dto/consumption/model/DailyList.java
  backend/src/main/java/backend/backend/dto/consumption/model/DailySumAmountQueryDTO.java
  backend/src/main/java/backend/backend/dto/consumption/model/TopExpense.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsDailyAnalyzeResponse.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryCustom.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryImpl.java
  backend/src/main/java/backend/backend/security/config/SecurityConfig.java
  backend/src/main/java/backend/backend/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/test/java/backend/backend/Repository/ConsumptionRepositoryTest.java
Labels: ✨feature, 백엔드
