Repository NLL-MoneyWise/MoneyWise, pull requests merged in 2025-04, with the labels that each got.

#62 [Refactor] 영수증, 소비저장 프로세스 코드 구조 개선
  backend/src/main/java/backend/backend/controller/ConsumptionController.java
  backend/src/main/java/backend/backend/controller/FacadeController.java
  backend/src/main/java/backend/backend/domain/Consumption.java
  backend/src/main/java/backend/backend/domain/Receipt.java
  backend/src/main/java/backend/backend/dto/common/model/Item.java
  backend/src/main/java/backend/backend/dto/consumption/model/ConsumptionItem.java
  backend/src/main/java/backend/backend/dto/consumption/request/ConsumptionsSaveRequest.java
  backend/src/main/java/backend/backend/dto/facade/response/FacadeReceiptProcessResponse.java
  backend/src/main/java/backend/backend/dto/receipt/response/ReceiptAnalyzeResponse.java
  backend/src/main/java/backend/backend/repository/ReceiptRepository.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/FacadeService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/test/java/backend/backend/controller/ConsumptionControllerTest.java
  backend/src/test/java/backend/backend/controller/FacadeControllerTest.java
  backend/src/test/java/backend/backend/controller/ReceiptControllerTest.java
  backend/src/test/java/backend/backend/service/ConsumptionServiceTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
Labels: ♻️ refactor, 백엔드

#61 로그인 및 회원가입 api 연동
  frontend/public/마스코트 울상.png
  frontend/public/마스코트.png
  frontend/public/행복한 마스코트.png
  frontend/src/app/(auth)/join/page.tsx
  frontend/src/app/(auth)/layout.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(common)/layout.tsx
  frontend/src/app/(kakaologin)/kakao-login/page.tsx
  frontend/src/app/(kakaologin)/layout.tsx
  frontend/src/app/(kakaologin)/login-failed/page.tsx
  frontend/src/app/(upload)/upload/page.tsx
  frontend/src/app/MockingProiver.tsx
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/components/SignUpForm/SignUpForm.tsx
  frontend/src/app/auth/hooks/useAuthMutation.ts
  frontend/src/app/auth/respository.ts
  frontend/src/app/auth/types/reponse/response-login.ts
  frontend/src/app/auth/types/request/request-login.ts
  frontend/src/app/auth/util/saveToekn.ts
  frontend/src/app/common/components/Articles/IntroduceArticle/IntroduceArticle.tsx
  frontend/src/app/common/components/Button/Button.tsx
  frontend/src/app/common/components/FileUpload/UploadButton.tsx
  frontend/src/app/common/components/Header/Header.tsx
  frontend/src/app/common/components/Input/InputField.tsx
  frontend/src/app/common/components/Link/Link.tsx
  frontend/src/app/common/components/Text/Text.tsx
  frontend/src/app/common/components/Toast/Toast.tsx
  frontend/src/app/common/types/error/error.ts
  frontend/src/app/common/util/api.ts
  frontend/src/app/common/util/errorHandler.ts
  frontend/src/stores/userStore.ts
Labels: ✨feature

#64 로그인 기능 수정
  frontend/public/찾을 수 없는 마스코트.png
  frontend/src/app/(auth)/layout.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(kakaologin)/kakao-login/page.tsx
  frontend/src/app/api/auth/check/route.ts
  frontend/src/app/api/auth/token/route.ts
  frontend/src/app/auth/api/action.ts
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/hooks/useAuthMutation.ts
  frontend/src/app/auth/respository.ts
  frontend/src/app/auth/types/reponse/index.ts
  frontend/src/app/auth/types/reponse/reponse-sign-up.ts
  frontend/src/app/auth/types/reponse/reponse-validate.ts
  frontend/src/app/auth/types/reponse/response-login.ts
  frontend/src/app/auth/types/request/index.ts
  frontend/src/app/auth/types/request/request-validate.ts
  frontend/src/app/auth/util/deleteToken.ts
  frontend/src/app/auth/util/getToken.ts
  frontend/src/app/auth/util/saveToekn.ts
  frontend/src/app/auth/util/toekn.ts
  frontend/src/app/common/components/ArrowIcon/ArrowIcon.tsx
  frontend/src/app/common/components/Articles/InstructionArticle/InstructionArticle.tsx
  frontend/src/app/common/components/Articles/IntroduceArticle/IntroduceArticle.tsx
  frontend/src/app/common/components/FloatingButton/FloatingButton.tsx
  frontend/src/app/common/components/Header/Header.tsx
  frontend/src/app/common/components/NavBar/NavBar.tsx
  frontend/src/app/common/components/Toast/Toast.tsx
  frontend/src/app/common/components/Toast/ToastContainer.tsx
  frontend/src/app/common/hooks/useClinetMount.ts
  frontend/src/app/common/hooks/useToastStore.tsx
  frontend/src/app/common/types/response/reponse.dto.ts
  frontend/src/app/common/util/api.ts
  frontend/src/app/layout.tsx
  frontend/src/app/not-found.tsx
  frontend/src/app/page.tsx
  frontend/src/middleware.ts
  frontend/src/stores/userStore.ts
Labels: ✨feature, 프론트엔드
