Repository NLL-MoneyWise/MoneyWise, pull requests merged in 2025-02, with the labels that each got.

#23 모바일 웹 디자인 설정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/issue_template.md
  frontend/src/app/globals.css
Labels: 🎨design, 프론트엔드

#26 Feature/receipt analyze
  .idea/.gitignore
  .idea/MoneyWise.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/backend/backend/config/RestTemplateConfig.java
  backend/src/main/java/backend/backend/config/S3Config.java
  backend/src/main/java/backend/backend/controller/ReceiptController.java
  backend/src/main/java/backend/backend/controller/UploadController.java
  backend/src/main/java/backend/backend/domain/Receipt.java
  backend/src/main/java/backend/backend/dto/request/OpenAiRequest.java
  backend/src/main/java/backend/backend/dto/response/OpenAiResponse.java
  backend/src/main/java/backend/backend/dto/response/ReceiptAnalyzeResponse.java
  backend/src/main/java/backend/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/backend/backend/exception/JsonParseException.java
  backend/src/main/java/backend/backend/exception/OpenAiApiException.java
  backend/src/main/java/backend/backend/repository/ReceiptRepository.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/main/java/backend/backend/service/S3Service.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/wallet/README
  backend/src/main/resources/wallet/cwallet.sso
  backend/src/main/resources/wallet/cwallet.sso.lck
  backend/src/main/resources/wallet/ewallet.p12
  backend/src/main/resources/wallet/ewallet.p12.lck
  backend/src/main/resources/wallet/ewallet.pem
  backend/src/main/resources/wallet/keystore.jks
  backend/src/main/resources/wallet/ojdbc.properties
  backend/src/main/resources/wallet/sqlnet.ora
  backend/src/main/resources/wallet/tnsnames.ora
  backend/src/main/resources/wallet/truststore.jks
  backend/src/test/java/backend/backend/controller/ReceiptControllerTest.java
  backend/src/test/java/backend/backend/controller/UploadControllerTest.java
  backend/src/test/java/backend/backend/service/ReceiptServiceTest.java
  backend/src/test/java/backend/backend/service/S3ServiceIntegrationTest.java
  backend/src/test/resources/application.properties
Labels: ✨feature, 백엔드

#34 로그인 개발
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/MockingProiver.tsx
  frontend/src/app/QueryProvider.tsx
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/hooks/useAuthMutation.ts
  frontend/src/app/auth/hooks/useValidateForm.ts
  frontend/src/app/auth/respository.ts
  frontend/src/app/auth/types/reponse/index.ts
  frontend/src/app/auth/types/reponse/response-login.ts
  frontend/src/app/auth/types/request/index.ts
  frontend/src/app/auth/types/request/request-login.ts
  frontend/src/app/common/components/Button/Button.tsx
  frontend/src/app/common/components/Input/InputField.tsx
  frontend/src/app/common/components/Toast/Toast.tsx
  frontend/src/app/common/components/Toast/ToastContainer.tsx
  frontend/src/app/common/components/TopBar/TopBar.tsx
  frontend/src/app/common/hooks/useToastStore.tsx
  frontend/src/app/common/types/error/error.ts
  frontend/src/app/common/types/response/reponse.dto.ts
  frontend/src/app/common/util/api.ts
  frontend/src/app/common/util/errorHandler.ts
  frontend/src/app/layout.tsx
  frontend/src/constants/errorMessage.ts
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: ✨feature, 프론트엔드

#35 feat: 년도 별, 년 월 별 소비를 분석하는 기능 구현
  backend/src/main/java/backend/backend/common/ErrorType.java
  backend/src/main/java/backend/backend/controller/AuthController.java
  backend/src/main/java/backend/backend/controller/ConsumptionController.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsYearMonthResponse.java
  backend/src/main/java/backend/backend/dto/consumption/response/ConsumptionsYearResponse.java
  backend/src/main/java/backend/backend/exception/APIException.java
  backend/src/main/java/backend/backend/exception/AuthException.java
  backend/src/main/java/backend/backend/exception/AuthenticationException.java
  backend/src/main/java/backend/backend/exception/ExternalServiceException.java
  backend/src/main/java/backend/backend/exception/InternalServerException.java
  backend/src/main/java/backend/backend/exception/InvalidInputException.java
  backend/src/main/java/backend/backend/exception/JsonParseException.java
  backend/src/main/java/backend/backend/exception/NotFoundException.java
  backend/src/main/java/backend/backend/exception/OpenAiApiException.java
  backend/src/main/java/backend/backend/exception/ValidationException.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepository.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryCustom.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryImpl.java
  backend/src/main/java/backend/backend/security/config/SecurityConfig.java
  backend/src/main/java/backend/backend/security/exception/CustomAuthenticationEntryPoint.java
  backend/src/main/java/backend/backend/security/jwt/JwtUtils.java
  backend/src/main/java/backend/backend/service/AuthService.java
  backend/src/main/java/backend/backend/service/ConsumptionService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/main/java/backend/backend/service/S3Service.java
  backend/src/main/java/backend/backend/service/UserService.java
  backend/src/test/java/backend/backend/Repository/ConsumptionRepositoryTest.java
  backend/src/test/java/backend/backend/controller/ConsumptionControllerTest.java
Labels: ✨feature, 백엔드

#37 로그인 로직 구현
  frontend/src/app/api/auth/token/route.ts
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/hooks/useAuthMutation.ts
  frontend/src/app/auth/types/reponse/response-login.ts
  frontend/src/app/auth/types/token/index.ts
  frontend/src/app/auth/util/deleteToken.ts
  frontend/src/app/auth/util/getToken.ts
  frontend/src/app/auth/util/saveToekn.ts
  frontend/src/app/common/types/error/error.ts
  frontend/src/middleware.ts
  frontend/src/mocks/handlers.js
  frontend/src/stores/userStore.ts
Labels: ✨feature, 프론트엔드

#40 회원가입 페이지 개발
  frontend/src/app/(auth)/join/page.tsx
  frontend/src/app/(auth)/layout.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/auth/components/LoginForm/LoginForm.tsx
  frontend/src/app/auth/components/SignUpForm/SignUpForm.tsx
  frontend/src/app/auth/hooks/useAuthMutation.ts
  frontend/src/app/auth/hooks/useValidateForm.ts
  frontend/src/app/auth/respository.ts
  frontend/src/app/auth/types/request/index.ts
  frontend/src/app/auth/types/request/request-signUp.ts
  frontend/src/app/common/components/Input/InputField.tsx
  frontend/src/app/common/util/debounce.ts
  frontend/src/mocks/handlers.js
Labels: ✨feature, 프론트엔드

#21 feat: 메모 생성, 수정, 조회 관련 기능 구현
  backend/src/main/java/backend/backend/BackendApplication.java
  backend/src/main/java/backend/backend/controller/MemoController.java
  backend/src/main/java/backend/backend/domain/Memo.java
  backend/src/main/java/backend/backend/dto/memo/model/MemoDTO.java
  backend/src/main/java/backend/backend/dto/memo/request/CreateMemoRequest.java
  backend/src/main/java/backend/backend/dto/memo/request/UpdateMemoRequest.java
  backend/src/main/java/backend/backend/dto/memo/response/CreateMemoResponse.java
  backend/src/main/java/backend/backend/dto/memo/response/GetAllMemosResponse.java
  backend/src/main/java/backend/backend/dto/memo/response/UpdateMemoResponse.java
  backend/src/main/java/backend/backend/repository/ConsumptionRepositoryCustom.java
  backend/src/main/java/backend/backend/repository/MemoRepository.java
  backend/src/main/java/backend/backend/service/MemoService.java
  backend/src/main/java/backend/backend/service/ReceiptService.java
  backend/src/test/java/backend/backend/controller/MemoControllerTest.java
Labels: ✨feature, 백엔드
